// Copyright Epic Games, Inc. All Rights Reserved.
// This source file is licensed solely to users who have
// accepted a valid Unreal Engine license agreement 
// (see e.g., https://www.unrealengine.com/eula), and use
// of this source file is governed by such agreement.

#pragma once

#include "oodlecore.h"

/*******

Callers (eg. OodleMalloc/Log) refer to OodlePlugin* functions/types/variables

The implementation makes either OodleCore_Plugin or OodleNet_Plugin

*******/

#ifdef OODLE_BUILDING_NETWORK

#include "../network/oodlenetplugins_gen.h"

#define t_fp_OodlePlugin_MallocAligned t_fp_OodleNet_Plugin_MallocAligned
#define t_fp_OodlePlugin_Free t_fp_OodleNet_Plugin_Free
#define OodlePlugins_SetAllocators OodleNet_Plugins_SetAllocators
#define t_fp_OodlePlugin_Printf t_fp_OodleNet_Plugin_Printf
#define OodlePlugins_SetPrintf OodleNet_Plugins_SetPrintf
#define t_fp_OodlePlugin_DisplayAssertion t_fp_OodleNet_Plugin_DisplayAssertion
#define OodlePlugins_SetAssertion OodleNet_Plugins_SetAssertion
#define OodlePlugin_MallocAligned_Default OodleNet_Plugin_MallocAligned_Default
#define OodlePlugin_Free_Default OodleNet_Plugin_Free_Default
#define OodlePlugin_Printf_Default OodleNet_Plugin_Printf_Default
#define OodlePlugin_Printf_Verbose OodleNet_Plugin_Printf_Verbose
#define OodlePlugin_DisplayAssertion_Default OodleNet_Plugin_DisplayAssertion_Default

#define g_fp_OodlePlugin_MallocAligned g_fp_OodleNet_Plugin_MallocAligned
#define g_fp_OodlePlugin_Free g_fp_OodleNet_Plugin_Free
#define g_fp_OodlePlugin_DisplayAssertion g_fp_OodleNet_Plugin_DisplayAssertion
#define g_fp_OodlePlugin_Printf g_fp_OodleNet_Plugin_Printf

#define t_fp_OodlePlugin_RunJob t_fp_OodleNet_Plugin_RunJob
#define t_fp_OodlePlugin_WaitJob t_fp_OodleNet_Plugin_WaitJob
#define OodlePlugins_SetJobSystemAndCount OodleNet_Plugins_SetJobSystemAndCount
#define OodlePlugins_GetJobTargetParallelism OodleNet_Plugin_GetJobTargetParallelism

#define g_fp_OodlePlugin_RunJob	g_fp_OodleNet_Plugin_RunJob
#define g_fp_OodlePlugin_WaitJob g_fp_OodleNet_Plugin_WaitJob
#define OodlePlugin_RunJob_Default OodleNet_Plugin_RunJob_Default

#elif defined(OODLE_BUILDING_TEXTURE)

#include "../texture/oodletexplugins_gen.h"

#define t_fp_OodlePlugin_MallocAligned t_fp_OodleTex_Plugin_MallocAligned
#define t_fp_OodlePlugin_Free t_fp_OodleTex_Plugin_Free
#define OodlePlugins_SetAllocators OodleTex_Plugins_SetAllocators
#define t_fp_OodlePlugin_Printf t_fp_OodleTex_Plugin_Printf
#define OodlePlugins_SetPrintf OodleTex_Plugins_SetPrintf
#define t_fp_OodlePlugin_DisplayAssertion t_fp_OodleTex_Plugin_DisplayAssertion
#define OodlePlugins_SetAssertion OodleTex_Plugins_SetAssertion
#define OodlePlugin_MallocAligned_Default OodleTex_Plugin_MallocAligned_Default
#define OodlePlugin_Free_Default OodleTex_Plugin_Free_Default
#define OodlePlugin_Printf_Default OodleTex_Plugin_Printf_Default
#define OodlePlugin_Printf_Verbose OodleTex_Plugin_Printf_Verbose
#define OodlePlugin_DisplayAssertion_Default OodleTex_Plugin_DisplayAssertion_Default

#define g_fp_OodlePlugin_MallocAligned g_fp_OodleTex_Plugin_MallocAligned
#define g_fp_OodlePlugin_Free g_fp_OodleTex_Plugin_Free
#define g_fp_OodlePlugin_DisplayAssertion g_fp_OodleTex_Plugin_DisplayAssertion
#define g_fp_OodlePlugin_Printf g_fp_OodleTex_Plugin_Printf

#define t_fp_OodlePlugin_RunJob t_fp_OodleTex_Plugin_RunJob
#define t_fp_OodlePlugin_WaitJob t_fp_OodleTex_Plugin_WaitJob
#define OodlePlugins_SetJobSystemAndCount OodleTex_Plugins_SetJobSystemAndCount
#define OodlePlugins_GetJobTargetParallelism OodleTex_Plugin_GetJobTargetParallelism

#define g_fp_OodlePlugin_RunJob	g_fp_OodleTex_Plugin_RunJob
#define g_fp_OodlePlugin_WaitJob g_fp_OodleTex_Plugin_WaitJob
#define OodlePlugin_RunJob_Default OodleTex_Plugin_RunJob_Default

#elif defined(OODLE_BUILDING_TEXTURERT)

#include "../texturert/oodletexrtplugins_gen.h"

#define t_fp_OodlePlugin_MallocAligned t_fp_OodleTexRT_Plugin_MallocAligned
#define t_fp_OodlePlugin_Free t_fp_OodleTexRT_Plugin_Free
#define OodlePlugins_SetAllocators OodleTexRT_Plugins_SetAllocators
#define t_fp_OodlePlugin_Printf t_fp_OodleTexRT_Plugin_Printf
#define OodlePlugins_SetPrintf OodleTexRT_Plugins_SetPrintf
#define t_fp_OodlePlugin_DisplayAssertion t_fp_OodleTexRT_Plugin_DisplayAssertion
#define OodlePlugins_SetAssertion OodleTexRT_Plugins_SetAssertion
#define OodlePlugin_MallocAligned_Default OodleTexRT_Plugin_MallocAligned_Default
#define OodlePlugin_Free_Default OodleTexRT_Plugin_Free_Default
#define OodlePlugin_Printf_Default OodleTexRT_Plugin_Printf_Default
#define OodlePlugin_Printf_Verbose OodleTexRT_Plugin_Printf_Verbose
#define OodlePlugin_DisplayAssertion_Default OodleTexRT_Plugin_DisplayAssertion_Default

#define g_fp_OodlePlugin_MallocAligned g_fp_OodleTexRT_Plugin_MallocAligned
#define g_fp_OodlePlugin_Free g_fp_OodleTexRT_Plugin_Free
#define g_fp_OodlePlugin_DisplayAssertion g_fp_OodleTexRT_Plugin_DisplayAssertion
#define g_fp_OodlePlugin_Printf g_fp_OodleTexRT_Plugin_Printf

#define t_fp_OodlePlugin_RunJob t_fp_OodleTexRT_Plugin_RunJob
#define t_fp_OodlePlugin_WaitJob t_fp_OodleTexRT_Plugin_WaitJob
#define OodlePlugins_SetJobSystemAndCount OodleTexRT_Plugins_SetJobSystemAndCount
#define OodlePlugins_GetJobTargetParallelism OodleTexRT_Plugin_GetJobTargetParallelism

#define g_fp_OodlePlugin_RunJob	g_fp_OodleTexRT_Plugin_RunJob
#define g_fp_OodlePlugin_WaitJob g_fp_OodleTexRT_Plugin_WaitJob
#define OodlePlugin_RunJob_Default OodleTexRT_Plugin_RunJob_Default

#else

#include "oodlecoreplugins_gen.h"

#define t_fp_OodlePlugin_MallocAligned t_fp_OodleCore_Plugin_MallocAligned
#define t_fp_OodlePlugin_Free t_fp_OodleCore_Plugin_Free
#define OodlePlugins_SetAllocators OodleCore_Plugins_SetAllocators
#define t_fp_OodlePlugin_Printf t_fp_OodleCore_Plugin_Printf
#define OodlePlugins_SetPrintf OodleCore_Plugins_SetPrintf
#define t_fp_OodlePlugin_DisplayAssertion t_fp_OodleCore_Plugin_DisplayAssertion
#define OodlePlugins_SetAssertion OodleCore_Plugins_SetAssertion
#define OodlePlugin_MallocAligned_Default OodleCore_Plugin_MallocAligned_Default
#define OodlePlugin_Free_Default OodleCore_Plugin_Free_Default
#define OodlePlugin_Printf_Default OodleCore_Plugin_Printf_Default
#define OodlePlugin_Printf_Verbose OodleCore_Plugin_Printf_Verbose
#define OodlePlugin_DisplayAssertion_Default OodleCore_Plugin_DisplayAssertion_Default

#define g_fp_OodlePlugin_MallocAligned g_fp_OodleCore_Plugin_MallocAligned
#define g_fp_OodlePlugin_Free g_fp_OodleCore_Plugin_Free
#define g_fp_OodlePlugin_DisplayAssertion g_fp_OodleCore_Plugin_DisplayAssertion
#define g_fp_OodlePlugin_Printf g_fp_OodleCore_Plugin_Printf

#define t_fp_OodlePlugin_RunJob t_fp_OodleCore_Plugin_RunJob
#define t_fp_OodlePlugin_WaitJob t_fp_OodleCore_Plugin_WaitJob
#define OodlePlugins_SetJobSystemAndCount OodleCore_Plugins_SetJobSystemAndCount
#define OodlePlugins_GetJobTargetParallelism OodleCore_Plugin_GetJobTargetParallelism

#define g_fp_OodlePlugin_RunJob	g_fp_OodleCore_Plugin_RunJob
#define g_fp_OodlePlugin_WaitJob g_fp_OodleCore_Plugin_WaitJob
#define OodlePlugin_RunJob_Default OodleCore_Plugin_RunJob_Default

#endif
