name: Release

on:
  workflow_run:
    workflows: [Build]
    types: [completed]

jobs:
  Release:
    runs-on: ubuntu-latest

    steps:
    - name: Download built artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts

    - name: Display structure of artifacts
      run: ls -R
      working-directory: artifacts
